name: TEST Zachodnia TV

on:
  workflow_dispatch:

jobs:
  test-zachodnia:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - name: Pobierz repozytorium
        uses: actions/checkout@v5

      - name: Ustaw Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Zainstaluj biblioteki
        run: |
          pip install requests playwright
          playwright install --with-deps chromium

      - name: Test Zachodnia TV
        run: python scripts/test_zachodnia.py
